(blink-cursor-mode 0)
;;(scroll-bar-mode 0)
(tool-bar-mode 0)
(menu-bar-mode 0)
(load-theme 'base16-solarized-dark)
(setq default-frame-alist '((font . "Source Code Pro 14")))
(setq inhibit-startup-message t)
(setq inhibit-startup-echo-area-message t)
(setq initial-scratch-message "#+TITLE: \n#+AUTHOR: You")
(global-hl-line-mode 1)
(set-face-background 'hl-line "#3e4446")
(set-face-foreground 'highlight nil)

(set-face-foreground 'highlight nil)
